name: Build and deploy JAR app to Azure Web App - FutpoolBack

on:
  push:
    branches: [ main ]
    paths:
      - 'back/**'                     # only backend files
      - 'back/pom.xml'
      - '.github/workflows/back-deploy.yml'  # run if this workflow changes
  pull_request:
    branches: [ main ]
    paths:
      - 'back/**'
      - 'back/pom.xml'
  workflow_dispatch: {}          

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: 'maven'

      # Put Firebase JSON into the app's resources BEFORE the build
      - name: Write Firebase credentials (raw JSON)
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: |
          mkdir -p back/src/main/resources/firebase
          printf '%s' "$FIREBASE_JSON" > back/src/main/resources/firebase/futbolapp-f50da-firebase-adminsdk-fbsvc-a1ab17138e.json

      - name: Build with Maven (in back/)
        working-directory: ./back
        run: mvn -B clean package -Dmaven.test.skip=true --no-transfer-progress

      - name: Create deploy package (zip)
        run: |
          mkdir -p deploy
          # copy jar from back/target and give it a stable name
          cp back/target/*-SNAPSHOT.jar deploy/app.jar
          # include firebase json if your app reads it from filesystem
          cp back/src/main/resources/firebase/futbolapp-f50da-firebase-adminsdk-fbsvc-a1ab17138e.json deploy/
          cd deploy && zip -r ../app.zip . && cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: deploy-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-zip
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ABDD78B3F70C4CB2A7980FCB248F024D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_88D44C35CF1F46FA9960B1FE36DF3F78 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_700DDBD4BC444BFC8EEF65390617FB66 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FutpoolBack'
          package: 'app.zip'










